name: Deploy Staging (Docker Hub)

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build and Push Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/safepick-frontend:staging .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/safepick-frontend:staging

  deploy:
    name: Pull and Run on VPS (Staging)
    runs-on: self-hosted
    needs: build

    steps:
      - name: Stop and Remove Old Container
        run: |
          docker stop safepick-frontend-staging || true
          docker rm safepick-frontend-staging || true

      - name: Pull Latest Image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/safepick-frontend:staging

      - name: Run New Container
        run: |
          docker run -d \
            --name safepick-frontend-staging \
            -p 8081:3000 \
            --restart unless-stopped \
            ${{ secrets.DOCKERHUB_USERNAME }}/safepick-frontend:staging

      - name: Clean Unused Images
        run: docker image prune
